# https://docs.ros.org/en/galactic/Tutorials/Parameters/Understanding-ROS2-Parameters.html#ros2params
/turtlesim2/sim:
   ros__parameters:
      background_b: 255
      background_g: 86
      background_r: 150
/**:
   ros__parameters:
      background_b: 255
      background_g: 86
      background_r: 150
